# -*- coding: utf-8 -*-
"""AppleHEALTH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bh3vY-W1CiVC_YN1pZgxNZZPSJA2luYy
"""

from google.colab import files
uploaded = files.upload()

"""Upload datasets👆"""

import pandas as pd

# Replace 'sleep_data.csv' with the exact file name if different
df = pd.read_csv('sleep_data.csv')

# Show first 5 rows
df.head()

df

"""load and view dataasets👆"""

# Remove any duplicate rows
df = df.drop_duplicates()

# Strip whitespace from column names (if any)
df.columns = df.columns.str.strip()

# Show basic info
df.info()

"""clean dataset👆"""

# Check missing values
df.isnull().sum()

# Example: Fill missing values with median (modify as needed)
df.fillna(df.median(numeric_only=True), inplace=True)

# Or drop rows with missing values (if very few)
# df.dropna(inplace=True)

"""handle missing values👆"""

# Define a function to remove outliers
def remove_outliers_iqr(data, columns):
    for col in columns:
        if pd.api.types.is_numeric_dtype(data[col]):
            Q1 = data[col].quantile(0.25)
            Q3 = data[col].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR
            data = data[(data[col] >= lower) & (data[col] <= upper)]
    return data

# Apply to numeric columns
df = remove_outliers_iqr(df, df.select_dtypes(include='number').columns)

df.shape  # Check the new shape

"""remove outliers👆"""

# Convert categorical column to category (if any)
# df['Gender'] = df['Gender'].astype('category')

# Normalize a numeric column (Min-Max Scaling)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Apply scaling to all numeric columns
df[df.select_dtypes(include='number').columns] = scaler.fit_transform(
    df.select_dtypes(include='number'))

df.head()



"""transform the data👆"""